#!/usr/bin/env node
/**
 * fetch-skus.mjs
 *
 * Pulls every product (and, optionally, every product variation) from a
 * WooCommerce store via the REST API and writes two files:
 *   - skus.csv  : SKU,URL[,Name,Type,Status]  (spreadsheet-friendly)
 *   - skus.md   : a Markdown table of the same data
 *
 * No external dependencies — uses Node 18+ built-in fetch.
 *
 * Usage:
 *   STORE_URL=https://zerotech.com.au \
 *   WC_KEY=ck_xxxxxxxxxxxxxxxx \
 *   WC_SECRET=cs_xxxxxxxxxxxxxxxx \
 *   node scripts/fetch-skus.mjs
 *
 * Options (env vars):
 *   INCLUDE_VARIATIONS=true   Also fetch each variable product's variations (default: true)
 *   STATUS=publish            Product status filter: publish | any | draft ... (default: publish)
 *   PER_PAGE=100              Page size, max 100 (default: 100)
 *   OUT_DIR=.                 Where to write skus.csv / skus.md (default: current dir)
 *
 * Get read-only API keys in WooCommerce:
 *   WooCommerce > Settings > Advanced > REST API > Add key  (Permissions: Read)
 */

import { writeFileSync, mkdirSync } from "node:fs";
import { join } from "node:path";

const STORE_URL = (process.env.STORE_URL || "").replace(/\/+$/, "");
const WC_KEY = process.env.WC_KEY || "";
const WC_SECRET = process.env.WC_SECRET || "";
const INCLUDE_VARIATIONS = (process.env.INCLUDE_VARIATIONS ?? "true") !== "false";
const STATUS = process.env.STATUS || "publish";
const PER_PAGE = Math.min(Number(process.env.PER_PAGE) || 100, 100);
const OUT_DIR = process.env.OUT_DIR || ".";

if (!STORE_URL || !WC_KEY || !WC_SECRET) {
  console.error(
    "Missing config. Set STORE_URL, WC_KEY and WC_SECRET environment variables.\n" +
      "Example:\n" +
      "  STORE_URL=https://zerotech.com.au WC_KEY=ck_... WC_SECRET=cs_... node scripts/fetch-skus.mjs"
  );
  process.exit(1);
}

const AUTH = "Basic " + Buffer.from(`${WC_KEY}:${WC_SECRET}`).toString("base64");

async function api(path, params = {}) {
  const url = new URL(`${STORE_URL}/wp-json/wc/v3/${path}`);
  for (const [k, v] of Object.entries(params)) url.searchParams.set(k, String(v));
  const res = await fetch(url, { headers: { Authorization: AUTH, Accept: "application/json" } });
  if (!res.ok) {
    const body = await res.text().catch(() => "");
    throw new Error(`GET ${url.pathname}${url.search} -> ${res.status} ${res.statusText}\n${body.slice(0, 500)}`);
  }
  const totalPages = Number(res.headers.get("x-wp-totalpages") || "1");
  const data = await res.json();
  return { data, totalPages };
}

/** Fetch every page of a paginated endpoint. */
async function fetchAll(path, params = {}) {
  const out = [];
  let page = 1;
  let totalPages = 1;
  do {
    const { data, totalPages: tp } = await api(path, { ...params, per_page: PER_PAGE, page });
    totalPages = tp;
    out.push(...data);
    process.stderr.write(`\r  ${path}: page ${page}/${totalPages} (${out.length} items)   `);
    page++;
  } while (page <= totalPages);
  process.stderr.write("\n");
  return out;
}

function csvCell(value) {
  const s = value == null ? "" : String(value);
  return /[",\n]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s;
}

async function main() {
  console.error(`Fetching products from ${STORE_URL} (status=${STATUS}, variations=${INCLUDE_VARIATIONS})...`);
  const products = await fetchAll("products", { status: STATUS });

  const rows = []; // { sku, url, name, type, status }
  for (const p of products) {
    if (p.sku) rows.push({ sku: p.sku, url: p.permalink, name: p.name, type: p.type, status: p.status });

    if (INCLUDE_VARIATIONS && p.type === "variable") {
      const variations = await fetchAll(`products/${p.id}/variations`, { status: STATUS });
      for (const v of variations) {
        if (v.sku) {
          rows.push({
            sku: v.sku,
            url: v.permalink || p.permalink,
            name: `${p.name}${v.attributes?.length ? " – " + v.attributes.map((a) => a.option).join(" / ") : ""}`,
            type: "variation",
            status: v.status || p.status,
          });
        }
      }
    }
  }

  // De-duplicate on SKU (keep first seen) and sort.
  const seen = new Set();
  const unique = rows
    .filter((r) => (seen.has(r.sku) ? false : seen.add(r.sku)))
    .sort((a, b) => a.sku.localeCompare(b.sku));

  mkdirSync(OUT_DIR, { recursive: true });

  // CSV
  const csv = [
    "SKU,URL,Name,Type,Status",
    ...unique.map((r) => [r.sku, r.url, r.name, r.type, r.status].map(csvCell).join(",")),
  ].join("\n");
  writeFileSync(join(OUT_DIR, "skus.csv"), csv + "\n");

  // Markdown
  const md = [
    `# Product SKUs and URLs`,
    ``,
    `Source: ${STORE_URL} · ${unique.length} SKUs · generated by \`scripts/fetch-skus.mjs\``,
    ``,
    `| SKU | URL | Name |`,
    `| --- | --- | --- |`,
    ...unique.map((r) => `| ${r.sku} | ${r.url} | ${(r.name || "").replace(/\|/g, "\\|")} |`),
    ``,
  ].join("\n");
  writeFileSync(join(OUT_DIR, "skus.md"), md);

  console.error(
    `\nDone. ${unique.length} unique SKUs written to ${join(OUT_DIR, "skus.csv")} and ${join(OUT_DIR, "skus.md")}.`
  );
}

main().catch((err) => {
  console.error("\nERROR:", err.message);
  process.exit(1);
});
